// ============================================================
// LE PENDU — Banque de mots
// Mots sans accents (clavier 26 lettres). Difficulté dérivée
// de la longueur : facile <=6, moyen 7-9, difficile >=10.
// Chaque mot a une courte définition affichée en fin de partie.
// 10 thèmes × 50 mots = 500 mots.
// ============================================================

const RAW_WORDS = {
  "Animaux": [
    ["CHAT", "Petit félin domestique aux griffes rétractiles."],
    ["CHIEN", "Mammifère domestique fidèle, souvent gardien ou compagnon."],
    ["LION", "Grand félin d'Afrique, surnommé le roi des animaux."],
    ["TIGRE", "Grand félin rayé, le plus grand des chats sauvages."],
    ["ELEPHANT", "Plus gros mammifère terrestre, doté d'une trompe."],
    ["GIRAFE", "Mammifère africain au très long cou."],
    ["ZEBRE", "Équidé africain rayé de noir et blanc."],
    ["SINGE", "Primate agile, souvent vivant dans les arbres."],
    ["OURS", "Grand mammifère plantigrade au pelage épais."],
    ["RENARD", "Petit canidé rusé à la queue touffue."],
    ["LOUP", "Canidé sauvage vivant en meute."],
    ["AIGLE", "Grand rapace aux serres puissantes."],
    ["HIBOU", "Rapace nocturne aux aigrettes de plumes."],
    ["DAUPHIN", "Mammifère marin intelligent et joueur."],
    ["BALEINE", "Plus grand mammifère marin du monde."],
    ["REQUIN", "Grand poisson cartilagineux, prédateur des océans."],
    ["TORTUE", "Reptile lent protégé par une carapace."],
    ["LEZARD", "Petit reptile à quatre pattes et longue queue."],
    ["PAPILLON", "Insecte aux ailes colorées, issu d'une chenille."],
    ["ABEILLE", "Insecte pollinisateur qui produit le miel."],
    ["KANGOUROU", "Marsupial australien qui se déplace par bonds."],
    ["HERISSON", "Petit mammifère couvert de piquants."],
    ["ECUREUIL", "Petit rongeur à la queue touffue, vit dans les arbres."],
    ["CROCODILE", "Grand reptile aquatique aux mâchoires puissantes."],
    ["FLAMANT", "Grand oiseau échassier au plumage rose."],
    ["PANTHERE", "Grand félin tacheté, souvent nocturne."],
    ["MANCHOT", "Oiseau marin des régions froides, incapable de voler."],
    ["CHOUETTE", "Rapace nocturne sans aigrettes."],
    ["SCORPION", "Arachnide venimeux muni d'un dard."],
    ["VACHE", "Mammifère domestique élevé pour son lait."],
    ["CHEVAL", "Grand mammifère domestique utilisé pour le transport."],
    ["MOUTON", "Mammifère domestique élevé pour sa laine."],
    ["CHEVRE", "Mammifère domestique cornu, cousin du mouton."],
    ["COCHON", "Mammifère domestique élevé pour sa viande."],
    ["POULE", "Oiseau de basse-cour qui pond des œufs."],
    ["CANARD", "Oiseau aquatique domestique ou sauvage."],
    ["OIE", "Grand oiseau aquatique au long cou."],
    ["DINDE", "Grand oiseau de basse-cour à la chair prisée."],
    ["LAPIN", "Petit mammifère aux longues oreilles."],
    ["SOURIS", "Petit rongeur très répandu."],
    ["RAT", "Rongeur de taille moyenne, souvent citadin."],
    ["TAUPE", "Petit mammifère fouisseur presque aveugle."],
    ["BLAIREAU", "Mammifère nocturne au pelage rayé noir et blanc."],
    ["CASTOR", "Rongeur bâtisseur de barrages."],
    ["LOUTRE", "Mammifère semi-aquatique au pelage épais."],
    ["PHOQUE", "Mammifère marin aux nageoires, vivant sur la banquise."],
    ["MORSE", "Grand mammifère marin aux longues défenses."],
    ["ORQUE", "Grand cétacé noir et blanc, aussi appelé épaulard."],
    ["HIPPOCAMPE", "Petit poisson à la silhouette de cheval marin."],
    ["IGUANE", "Grand lézard tropical à la crête dorsale."]
  ],
  "Cuisine": [
    ["PAIN", "Aliment de base fait de farine, d'eau et de levure."],
    ["FROMAGE", "Produit laitier fermenté, souvent à base de lait de vache."],
    ["BEURRE", "Matière grasse obtenue en battant la crème."],
    ["POULET", "Volaille très consommée en cuisine."],
    ["TOMATE", "Fruit rouge utilisé comme légume en cuisine."],
    ["CAROTTE", "Légume racine orange, riche en vitamines."],
    ["POMME", "Fruit rond à pépins, souvent croquant."],
    ["BANANE", "Fruit tropical allongé et jaune à maturité."],
    ["CITRON", "Agrume acide utilisé pour assaisonner."],
    ["CHOCOLAT", "Confiserie à base de fèves de cacao."],
    ["GATEAU", "Pâtisserie sucrée cuite au four."],
    ["SOUPE", "Plat liquide chaud, souvent à base de légumes."],
    ["SALADE", "Plat froid de légumes ou de crudités."],
    ["OMELETTE", "Plat d'œufs battus cuits à la poêle."],
    ["RATATOUILLE", "Plat provençal de légumes mijotés."],
    ["CROISSANT", "Viennoiserie feuilletée en forme de croissant de lune."],
    ["BAGUETTE", "Pain long et fin typique de France."],
    ["QUICHE", "Tarte salée garnie d'œufs et de crème."],
    ["CREPE", "Fine galette de blé, sucrée ou salée."],
    ["MACARON", "Petit gâteau rond à base de meringue et d'amande."],
    ["RISOTTO", "Plat italien de riz crémeux mijoté."],
    ["LASAGNE", "Plat italien de pâtes en couches avec sauce."],
    ["MOUTARDE", "Condiment piquant à base de graines moulues."],
    ["VINAIGRE", "Liquide acide utilisé pour assaisonner."],
    ["CASSEROLE", "Ustensile de cuisine à manche pour cuire les aliments."],
    ["MARMITE", "Grand récipient pour cuire des plats mijotés."],
    ["SEL", "Condiment minéral utilisé pour assaisonner les plats."],
    ["POIVRE", "Épice piquante issue de baies séchées."],
    ["HUILE", "Matière grasse liquide utilisée en cuisine."],
    ["SUCRE", "Substance sucrée extraite de la canne ou de la betterave."],
    ["FARINE", "Poudre obtenue en broyant des céréales."],
    ["OEUF", "Aliment pondu par une poule, riche en protéines."],
    ["LAIT", "Liquide blanc produit par les mammifères femelles."],
    ["RIZ", "Céréale cultivée en rizière, base de nombreux plats."],
    ["PATES", "Aliment à base de blé, souvent servi avec une sauce."],
    ["PIZZA", "Plat italien à base de pâte garnie et cuite au four."],
    ["SANDWICH", "Repas rapide fait de tranches de pain garnies."],
    ["HAMBURGER", "Sandwich rond composé d'un steak haché."],
    ["YAOURT", "Produit laitier fermenté et crémeux."],
    ["CONFITURE", "Préparation sucrée à base de fruits cuits."],
    ["MIEL", "Substance sucrée produite par les abeilles."],
    ["EPICE", "Substance végétale utilisée pour parfumer les plats."],
    ["CANNELLE", "Épice aromatique tirée de l'écorce d'un arbre."],
    ["GINGEMBRE", "Racine piquante utilisée en cuisine et en tisane."],
    ["AIL", "Bulbe piquant utilisé pour assaisonner les plats."],
    ["OIGNON", "Légume bulbeux à l'odeur piquante."],
    ["POIREAU", "Légume long à la saveur douce, cousin de l'oignon."],
    ["COURGETTE", "Légume vert allongé de la famille des cucurbitacées."],
    ["AUBERGINE", "Légume violet à la chair tendre."],
    ["CHAMPIGNON", "Organisme non végétal parfois comestible, poussant en terre."]
  ],
  "Geographie": [
    ["FRANCE", "Pays d'Europe de l'Ouest, capitale Paris."],
    ["PARIS", "Capitale de la France, ville lumière."],
    ["MONTAGNE", "Relief élevé de la Terre, souvent rocheux."],
    ["RIVIERE", "Cours d'eau qui se jette dans un fleuve."],
    ["OCEAN", "Vaste étendue d'eau salée entre les continents."],
    ["DESERT", "Région très sèche avec peu de végétation."],
    ["FORET", "Vaste étendue couverte d'arbres."],
    ["ILE", "Terre entourée d'eau de tous côtés."],
    ["VOLCAN", "Relief d'où peut jaillir de la lave."],
    ["CONTINENT", "Vaste étendue de terre, comme l'Afrique ou l'Asie."],
    ["AFRIQUE", "Continent au sud de l'Europe, berceau de l'humanité."],
    ["EUROPE", "Continent qui comprend la France, l'Allemagne, l'Italie..."],
    ["ASIE", "Plus grand continent du monde."],
    ["CANADA", "Pays d'Amérique du Nord, capitale Ottawa."],
    ["JAPON", "Pays insulaire d'Asie, capitale Tokyo."],
    ["BRESIL", "Plus grand pays d'Amérique du Sud."],
    ["EGYPTE", "Pays d'Afrique du Nord, célèbre pour ses pyramides."],
    ["ITALIE", "Pays d'Europe du Sud en forme de botte."],
    ["ESPAGNE", "Pays d'Europe du Sud, capitale Madrid."],
    ["ALLEMAGNE", "Pays d'Europe centrale, capitale Berlin."],
    ["SENEGAL", "Pays d'Afrique de l'Ouest, capitale Dakar."],
    ["RWANDA", "Pays d'Afrique de l'Est, surnommé le pays des mille collines."],
    ["FRONTIERE", "Limite qui sépare deux territoires."],
    ["CAPITALE", "Ville principale d'un pays, siège du gouvernement."],
    ["PENINSULE", "Terre entourée d'eau sauf sur un côté."],
    ["FLEUVE", "Cours d'eau qui se jette dans la mer."],
    ["LAC", "Grande étendue d'eau douce entourée de terre."],
    ["VALLEE", "Dépression allongée entre deux reliefs."],
    ["PLAINE", "Vaste étendue de terre plate."],
    ["GLACIER", "Grande masse de glace qui se déplace lentement."],
    ["ARCHIPEL", "Groupe d'îles proches les unes des autres."],
    ["EQUATEUR", "Ligne imaginaire qui divise la Terre en deux hémisphères."],
    ["POLE", "Extrémité de l'axe de rotation de la Terre."],
    ["HEMISPHERE", "Moitié du globe terrestre, nord ou sud."],
    ["LATITUDE", "Coordonnée qui indique la position nord-sud sur Terre."],
    ["LONGITUDE", "Coordonnée qui indique la position est-ouest sur Terre."],
    ["ATLAS", "Recueil de cartes géographiques."],
    ["USA", "Pays d'Amérique du Nord, capitale Washington."],
    ["CHINE", "Pays d'Asie le plus peuplé du monde."],
    ["INDE", "Grand pays d'Asie du Sud, capitale New Delhi."],
    ["MAROC", "Pays d'Afrique du Nord, capitale Rabat."],
    ["ALGERIE", "Plus grand pays d'Afrique par la superficie."],
    ["TUNISIE", "Pays d'Afrique du Nord, capitale Tunis."],
    ["KENYA", "Pays d'Afrique de l'Est connu pour ses safaris."],
    ["NIGERIA", "Pays d'Afrique de l'Ouest le plus peuplé."],
    ["MEXIQUE", "Pays d'Amérique du Nord, capitale Mexico."],
    ["ARGENTINE", "Grand pays d'Amérique du Sud, capitale Buenos Aires."],
    ["PORTUGAL", "Pays d'Europe du Sud-Ouest, capitale Lisbonne."],
    ["SUISSE", "Pays d'Europe centrale connu pour ses montagnes."],
    ["BELGIQUE", "Pays d'Europe de l'Ouest, capitale Bruxelles."]
  ],
  "Informatique & Cyber": [
    ["ORDINATEUR", "Machine électronique qui traite des données."],
    ["RESEAU", "Ensemble d'appareils connectés entre eux."],
    ["LOGICIEL", "Programme informatique installé sur un appareil."],
    ["CLAVIER", "Périphérique servant à taper du texte."],
    ["ECRAN", "Périphérique qui affiche les images d'un appareil."],
    ["SERVEUR", "Ordinateur qui fournit des ressources à d'autres machines."],
    ["PIRATE", "Personne qui s'introduit illégalement dans un système."],
    ["VIRUS", "Programme malveillant qui infecte un système."],
    ["PAREFEU", "Dispositif qui filtre le trafic réseau pour protéger un système."],
    ["CRYPTAGE", "Transformation d'une donnée pour la rendre illisible sans clé."],
    ["ALGORITHME", "Suite d'instructions pour résoudre un problème."],
    ["DONNEES", "Informations traitées ou stockées par un système."],
    ["NUAGE", "Infrastructure informatique accessible via Internet (cloud)."],
    ["ROBOT", "Machine capable d'exécuter des tâches automatiquement."],
    ["INTERNET", "Réseau mondial reliant des millions d'ordinateurs."],
    ["NAVIGATEUR", "Logiciel utilisé pour consulter des pages web."],
    ["FICHIER", "Ensemble de données enregistré sous un nom."],
    ["MEMOIRE", "Composant qui stocke temporairement ou durablement des données."],
    ["PROCESSEUR", "Composant qui exécute les instructions d'un ordinateur."],
    ["SAUVEGARDE", "Copie de sécurité de données."],
    ["AUTHENTIFICATION", "Vérification de l'identité d'un utilisateur."],
    ["VULNERABILITE", "Faille exploitable dans un système informatique."],
    ["HAMECONNAGE", "Technique frauduleuse pour voler des informations personnelles (phishing)."],
    ["RANCONGICIEL", "Logiciel malveillant qui bloque des données contre rançon."],
    ["AUDIT", "Examen méthodique pour évaluer la conformité d'un système."],
    ["GOUVERNANCE", "Ensemble des règles qui encadrent la gestion d'une organisation."],
    ["CODE", "Ensemble d'instructions écrites pour un programme."],
    ["PROGRAMME", "Suite d'instructions exécutée par un ordinateur."],
    ["APPLICATION", "Logiciel conçu pour une tâche précise."],
    ["SITE", "Ensemble de pages accessibles sur le web."],
    ["LIEN", "Élément cliquable qui mène vers une autre page."],
    ["TELECHARGER", "Copier un fichier depuis Internet vers son appareil."],
    ["IMPRIMANTE", "Périphérique qui reproduit un document sur papier."],
    ["ROUTEUR", "Appareil qui dirige le trafic d'un réseau."],
    ["WIFI", "Technologie de connexion sans fil à un réseau."],
    ["BLUETOOTH", "Technologie de connexion sans fil courte distance."],
    ["USB", "Norme de connexion utilisée pour brancher des périphériques."],
    ["DISQUE", "Support qui stocke des données informatiques."],
    ["PIXEL", "Plus petit point qui compose une image numérique."],
    ["INTERFACE", "Espace où l'utilisateur interagit avec un système."],
    ["PROTOCOLE", "Ensemble de règles régissant une communication informatique."],
    ["CHIFFREMENT", "Procédé qui rend une information illisible sans clé."],
    ["JETON", "Élément numérique utilisé pour authentifier un accès."],
    ["IDENTIFIANT", "Nom ou code unique servant à reconnaître un utilisateur."],
    ["INCIDENT", "Événement qui perturbe le fonctionnement normal d'un système."],
    ["MENACE", "Danger potentiel pesant sur un système informatique."],
    ["RISQUE", "Probabilité qu'une menace cause un dommage."],
    ["CONFORMITE", "Respect des règles et normes en vigueur."],
    ["SECURITE", "Ensemble des mesures qui protègent un système."],
    ["CYBERATTAQUE", "Action malveillante visant à compromettre un système informatique."]
  ],
  "Sport": [
    ["BASKET", "Sport d'équipe où l'on marque des paniers."],
    ["TENNIS", "Sport de raquette joué en simple ou en double."],
    ["NATATION", "Sport consistant à nager dans l'eau."],
    ["CYCLISME", "Sport pratiqué à vélo."],
    ["JUDO", "Art martial japonais basé sur les projections."],
    ["RUGBY", "Sport d'équipe où l'on porte un ballon ovale."],
    ["MARATHON", "Course à pied de 42,195 kilomètres."],
    ["ESCALADE", "Sport consistant à grimper une paroi."],
    ["VOLLEYBALL", "Sport d'équipe où le ballon ne doit pas toucher le sol."],
    ["HANDBALL", "Sport d'équipe où l'on marque avec un ballon à la main."],
    ["ATHLETISME", "Ensemble de disciplines de course, saut et lancer."],
    ["BOXE", "Sport de combat avec les poings."],
    ["ESCRIME", "Sport de combat à l'épée."],
    ["SKI", "Sport de glisse sur la neige."],
    ["SURF", "Sport de glisse sur les vagues."],
    ["GOLF", "Sport où l'on envoie une balle dans des trous avec un club."],
    ["HALTEROPHILIE", "Sport consistant à soulever des poids."],
    ["KARATE", "Art martial japonais fondé sur les coups portés à mains nues."],
    ["TAEKWONDO", "Art martial coréen misant sur les techniques de jambe."],
    ["AVIRON", "Sport nautique où l'on propulse un bateau avec des rames."],
    ["VOILE", "Sport nautique pratiqué sur un bateau propulsé par le vent."],
    ["PLONGEON", "Sport consistant à sauter avec style dans l'eau."],
    ["GYMNASTIQUE", "Sport combinant souplesse, force et acrobaties."],
    ["PATINAGE", "Sport de glisse pratiqué sur des patins."],
    ["HOCKEY", "Sport d'équipe joué avec une crosse et un palet ou une balle."],
    ["BASEBALL", "Sport d'équipe américain joué avec une batte et une balle."],
    ["CRICKET", "Sport d'équipe britannique joué avec une batte et une balle."],
    ["BADMINTON", "Sport de raquette joué avec un volant."],
    ["SQUASH", "Sport de raquette joué dans un espace fermé."],
    ["PETANQUE", "Jeu de boules typique du sud de la France."],
    ["BOWLING", "Jeu consistant à faire tomber des quilles avec une boule."],
    ["EQUITATION", "Sport pratiqué à dos de cheval."],
    ["TIR", "Sport consistant à atteindre une cible avec une arme."],
    ["ARCHERIE", "Sport consistant à tirer des flèches avec un arc."],
    ["TRIATHLON", "Épreuve combinant natation, cyclisme et course à pied."],
    ["DECATHLON", "Épreuve d'athlétisme regroupant dix disciplines."],
    ["RELAIS", "Course d'équipe où un témoin passe de coureur en coureur."],
    ["PENTATHLON", "Épreuve combinant cinq disciplines sportives différentes."],
    ["CANOE", "Petite embarcation propulsée à la pagaie simple."],
    ["KAYAK", "Petite embarcation propulsée à la pagaie double."],
    ["LUTTE", "Sport de combat au corps à corps sans coups."],
    ["SUMO", "Sport de combat japonais où l'on pousse l'adversaire hors du cercle."],
    ["CURLING", "Sport où l'on glisse des pierres sur la glace vers une cible."],
    ["BOBSLEIGH", "Sport de glisse en équipe sur une piste de glace."],
    ["LUGE", "Sport de glisse pratiqué allongé sur un traîneau."],
    ["MOTOCROSS", "Course de moto sur un circuit tout-terrain accidenté."],
    ["SKATEBOARD", "Sport de glisse pratiqué sur une planche à roulettes."],
    ["ROLLER", "Sport de glisse pratiqué avec des patins à roulettes."],
    ["TRAMPOLINE", "Sport consistant à effectuer des sauts sur une toile tendue."],
    ["FLECHETTES", "Jeu consistant à lancer des fléchettes sur une cible."]
  ],
  "Cinema & Culture": [
    ["CINEMA", "Art de raconter des histoires en images animées."],
    ["ACTEUR", "Personne qui interprète un rôle dans un film ou une pièce."],
    ["REALISATEUR", "Personne qui dirige la réalisation d'un film."],
    ["SCENARIO", "Texte qui décrit l'histoire et les dialogues d'un film."],
    ["MUSIQUE", "Art d'organiser des sons dans le temps."],
    ["PEINTURE", "Art de représenter des images avec de la couleur."],
    ["SCULPTURE", "Art de façonner une matière pour créer une forme en volume."],
    ["FESTIVAL", "Événement culturel organisé sur plusieurs jours."],
    ["ORCHESTRE", "Grand groupe de musiciens jouant ensemble."],
    ["GUITARE", "Instrument à cordes pincées."],
    ["PIANO", "Instrument à clavier et à cordes frappées."],
    ["DANSE", "Art de bouger le corps en rythme."],
    ["PHOTOGRAPHIE", "Art de capturer des images grâce à la lumière."],
    ["DOCUMENTAIRE", "Film qui présente des faits réels."],
    ["ANIMATION", "Film créé image par image, souvent en dessin ou en 3D."],
    ["COMEDIE", "Film ou pièce destiné à faire rire."],
    ["DRAME", "Œuvre centrée sur des émotions fortes et sérieuses."],
    ["THRILLER", "Film à suspense qui tient en haleine."],
    ["WESTERN", "Film se déroulant dans l'Ouest américain du XIXe siècle."],
    ["ACTRICE", "Femme qui interprète un rôle dans un film ou une pièce."],
    ["PRODUCTEUR", "Personne qui finance et supervise un film."],
    ["MONTAGE", "Assemblage des scènes d'un film."],
    ["CAMERA", "Appareil qui capture des images animées."],
    ["PROJECTEUR", "Appareil qui diffuse un film sur un écran."],
    ["SOUSTITRE", "Texte affiché en bas de l'écran pour traduire les dialogues."],
    ["BANDEANNONCE", "Court extrait promotionnel d'un film."],
    ["TOURNAGE", "Période durant laquelle un film est filmé."],
    ["DECOR", "Élément visuel qui recrée un lieu sur un plateau."],
    ["COSTUME", "Vêtement porté par un acteur pour incarner son personnage."],
    ["MAQUILLAGE", "Application de produits pour transformer l'apparence d'un acteur."],
    ["TRUCAGE", "Technique utilisée pour créer un effet visuel irréel."],
    ["CASTING", "Sélection des acteurs pour un film."],
    ["GENERIQUE", "Liste défilante des noms des personnes ayant participé à une œuvre."],
    ["SCENE", "Unité d'action dans un film ou une pièce."],
    ["PLATEAU", "Lieu où l'on tourne un film ou une émission."],
    ["DIALOGUE", "Échange de paroles entre les personnages d'une œuvre."],
    ["PERSONNAGE", "Individu fictif qui évolue dans une histoire."],
    ["INTRIGUE", "Enchaînement des événements qui composent une histoire."],
    ["SPECTACLE", "Représentation destinée à être vue par un public."],
    ["CONCERT", "Représentation musicale donnée devant un public."],
    ["CHANSON", "Courte œuvre musicale chantée avec des paroles."],
    ["MELODIE", "Suite de notes qui forme un air musical."],
    ["RYTHME", "Organisation de la musique dans le temps."],
    ["PARTITION", "Notation écrite d'une œuvre musicale."],
    ["VIOLON", "Instrument à cordes frottées avec un archet."],
    ["TROMPETTE", "Instrument à vent en cuivre."],
    ["BATTERIE", "Ensemble d'instruments de percussion joué avec des baguettes."],
    ["SAXOPHONE", "Instrument à vent en métal, souvent utilisé en jazz."],
    ["CHOEUR", "Groupe de chanteurs interprétant ensemble une œuvre."],
    ["BALLET", "Spectacle de danse classique souvent accompagné de musique."]
  ],
  "Theatre": [
    ["THEATRE", "Art de jouer une histoire devant un public."],
    ["TRAGEDIE", "Pièce de théâtre au dénouement funeste et grave."],
    ["COMEDIEN", "Personne qui interprète un rôle au théâtre."],
    ["DRAMATURGE", "Auteur qui écrit des pièces de théâtre."],
    ["REPERTOIRE", "Ensemble des œuvres qu'une troupe peut jouer."],
    ["MISEENSCENE", "Organisation visuelle et scénique d'une pièce."],
    ["MONOLOGUE", "Long discours d'un personnage seul en scène."],
    ["REPLIQUE", "Phrase prononcée par un personnage en réponse à un autre."],
    ["RIDEAU", "Grand tissu qui masque la scène avant le spectacle."],
    ["COULISSE", "Espace caché derrière ou à côté de la scène."],
    ["SCENOGRAPHIE", "Art de concevoir l'espace scénique d'un spectacle."],
    ["TRAGEDIEN", "Acteur spécialisé dans les rôles tragiques."],
    ["MASQUE", "Objet qui couvre le visage d'un acteur."],
    ["VAUDEVILLE", "Comédie légère fondée sur des quiproquos."],
    ["FARCE", "Pièce comique courte et bouffonne."],
    ["PANTOMIME", "Art de raconter une histoire par le geste, sans parole."],
    ["MARIONNETTE", "Figurine articulée manipulée par un acteur caché."],
    ["IMPROVISATION", "Jeu théâtral inventé sur le moment, sans texte préparé."],
    ["REPETITION", "Séance de travail préparant une représentation."],
    ["ACTE", "Grande division d'une pièce de théâtre."],
    ["SPECTATEUR", "Personne qui assiste à une représentation."],
    ["APPLAUDISSEMENT", "Battement de mains pour saluer une performance."],
    ["ESTRADE", "Plateforme surélevée où se produit un artiste."],
    ["LOGE", "Petite pièce où un acteur se prépare."],
    ["PROMPTEUR", "Personne ou appareil qui souffle le texte à un acteur."],
    ["ECLAIRAGE", "Ensemble des lumières qui mettent en valeur une scène."],
    ["SPOT", "Petit projecteur qui éclaire un point précis de la scène."],
    ["TROUPE", "Groupe de comédiens qui jouent ensemble."],
    ["REGISSEUR", "Personne qui coordonne le déroulement technique d'un spectacle."],
    ["CLASSIQUE", "Œuvre théâtrale issue d'un répertoire ancien et reconnu."],
    ["ABSURDE", "Courant théâtral qui met en scène l'incohérence de l'existence."],
    ["SATIRE", "Œuvre qui critique la société avec ironie."],
    ["CORYPHEE", "Chef du chœur dans le théâtre antique."],
    ["PROLOGUE", "Texte d'introduction placé avant le début d'une pièce."],
    ["EPILOGUE", "Texte de conclusion placé après la fin d'une pièce."],
    ["DENOUEMENT", "Manière dont se résout l'intrigue à la fin."],
    ["PERIPETIE", "Événement imprévu qui fait rebondir l'action."],
    ["QUIPROQUO", "Malentendu comique où l'on prend une personne pour une autre."],
    ["ALEXANDRIN", "Vers classique français de douze syllabes."],
    ["SOLILOQUE", "Discours qu'un personnage se tient à lui-même."],
    ["AVANTSCENE", "Partie de la scène la plus proche du public."],
    ["BALCON", "Étage surélevé d'une salle de théâtre."],
    ["PARTERRE", "Rangée de sièges au rez-de-chaussée d'une salle de théâtre."],
    ["ENTRACTE", "Pause entre deux actes d'un spectacle."],
    ["REPRESENTATION", "Séance au cours de laquelle une œuvre est jouée devant un public."],
    ["CRITIQUE", "Analyse ou jugement porté sur une œuvre."],
    ["AFFICHE", "Support imprimé annonçant un spectacle."],
    ["TOURNEE", "Série de représentations données dans différentes villes."],
    ["COMPAGNIE", "Groupe d'artistes qui produisent des spectacles ensemble."],
    ["SCENARISTE", "Personne qui écrit le texte destiné à être joué ou filmé."]
  ],
  "Litterature": [
    ["ROMAN", "Long récit de fiction en prose."],
    ["POEME", "Texte écrit avec un rythme et souvent des rimes."],
    ["NOUVELLE", "Récit de fiction plus court qu'un roman."],
    ["CONTE", "Récit court, souvent merveilleux, transmis par tradition."],
    ["FABLE", "Court récit illustrant une morale, souvent avec des animaux."],
    ["ESSAI", "Texte qui développe une réflexion sur un sujet."],
    ["BIOGRAPHIE", "Récit de la vie d'une personne écrit par un autre."],
    ["AUTOBIOGRAPHIE", "Récit de la vie d'un auteur écrit par lui-même."],
    ["RECIT", "Texte qui raconte une suite d'événements."],
    ["NARRATEUR", "Voix qui raconte l'histoire dans un texte."],
    ["PROTAGONISTE", "Personnage principal d'une histoire."],
    ["ANTAGONISTE", "Personnage qui s'oppose au héros d'une histoire."],
    ["TRAME", "Fil conducteur des événements d'une histoire."],
    ["CHAPITRE", "Grande division d'un livre."],
    ["PARAGRAPHE", "Section d'un texte marquée par un retour à la ligne."],
    ["STROPHE", "Groupe de vers formant une unité dans un poème."],
    ["RIME", "Répétition d'un même son à la fin de deux vers."],
    ["METAPHORE", "Figure de style qui compare sans mot de comparaison."],
    ["SYMBOLE", "Élément qui représente une idée abstraite."],
    ["STYLE", "Manière personnelle d'écrire d'un auteur."],
    ["GENRE", "Catégorie à laquelle appartient une œuvre littéraire."],
    ["ECRIVAIN", "Personne qui écrit des œuvres littéraires."],
    ["AUTEUR", "Personne qui a créé une œuvre écrite."],
    ["POETE", "Personne qui écrit des poèmes."],
    ["ROMANCIER", "Auteur spécialisé dans l'écriture de romans."],
    ["EDITEUR", "Personne ou maison qui publie des livres."],
    ["EDITION", "Publication d'une œuvre sous une forme donnée."],
    ["MANUSCRIT", "Texte original d'un auteur avant publication."],
    ["BROUILLON", "Première version non définitive d'un texte."],
    ["PUBLICATION", "Action de rendre un texte accessible au public."],
    ["LECTEUR", "Personne qui lit une œuvre."],
    ["BIBLIOTHEQUE", "Lieu où sont conservés et prêtés des livres."],
    ["LIBRAIRIE", "Commerce où l'on vend des livres."],
    ["COUVERTURE", "Page extérieure protégeant un livre."],
    ["PREFACE", "Texte d'introduction placé au début d'un livre."],
    ["SOMMAIRE", "Liste des parties d'un livre avec leur emplacement."],
    ["CITATION", "Passage d'un texte repris tel quel."],
    ["DEDICACE", "Mot personnel qu'un auteur écrit pour un lecteur."],
    ["PSEUDONYME", "Nom d'emprunt utilisé par un auteur."],
    ["BESTSELLER", "Livre qui connaît un grand succès de vente."],
    ["SAGA", "Longue histoire familiale ou héroïque en plusieurs parties."],
    ["TRILOGIE", "Œuvre composée de trois parties liées."],
    ["EPOPEE", "Long récit poétique qui célèbre des exploits héroïques."],
    ["MYTHE", "Récit traditionnel mettant en scène des figures surnaturelles."],
    ["LEGENDE", "Récit populaire mêlant histoire et merveilleux."],
    ["ALLEGORIE", "Représentation d'une idée abstraite par une image concrète."],
    ["IRONIE", "Procédé qui dit le contraire de ce que l'on pense pour se moquer."],
    ["PARODIE", "Imitation comique d'une œuvre sérieuse."],
    ["DESCRIPTION", "Passage qui détaille un lieu, un personnage ou une scène."],
    ["PERSONNAGE", "Individu fictif qui évolue dans une histoire."]
  ],
  "Football": [
    ["FOOTBALL", "Sport d'équipe où l'on marque des buts avec un ballon rond."],
    ["BALLON", "Objet rond utilisé pour jouer au football."],
    ["BUT", "Point marqué quand le ballon franchit la ligne adverse."],
    ["GARDIEN", "Joueur chargé de défendre les cages."],
    ["DEFENSEUR", "Joueur chargé d'empêcher l'adversaire de marquer."],
    ["MILIEU", "Joueur qui évolue au centre du terrain."],
    ["ATTAQUANT", "Joueur chargé de marquer des buts."],
    ["CAPITAINE", "Joueur qui porte le brassard et représente l'équipe."],
    ["ARBITRE", "Personne qui fait respecter les règles du match."],
    ["TOUCHE", "Remise en jeu du ballon depuis la ligne de côté."],
    ["CORNER", "Coup de pied de coin accordé après une sortie de but."],
    ["PENALTY", "Tir accordé après une faute dans la surface de réparation."],
    ["HORSJEU", "Position irrégulière d'un attaquant devant la défense."],
    ["CARTON", "Sanction disciplinaire montrée par l'arbitre, jaune ou rouge."],
    ["FAUTE", "Action irrégulière sanctionnée par l'arbitre."],
    ["COUPFRANC", "Coup de pied accordé après une faute."],
    ["TIR", "Frappe du ballon en direction du but."],
    ["PASSE", "Transmission du ballon à un coéquipier."],
    ["DRIBBLE", "Action de contourner un adversaire avec le ballon."],
    ["TACLE", "Geste défensif pour récupérer le ballon au sol."],
    ["CENTRE", "Passe envoyée depuis le côté vers la surface adverse."],
    ["TETE", "Frappe du ballon avec la tête."],
    ["POTEAU", "Montant vertical qui délimite les buts."],
    ["FILET", "Tissu tendu derrière les buts pour arrêter le ballon."],
    ["TERRAIN", "Surface de jeu où se déroule le match."],
    ["PELOUSE", "Herbe qui recouvre le terrain de football."],
    ["VESTIAIRE", "Pièce où les joueurs se changent avant et après le match."],
    ["MAILLOT", "Vêtement porté par un joueur, aux couleurs de son équipe."],
    ["CRAMPON", "Chaussure à pointes utilisée pour jouer au football."],
    ["SIFFLET", "Instrument utilisé par l'arbitre pour signaler une décision."],
    ["MITEMPS", "Pause au milieu d'un match."],
    ["PROLONGATION", "Temps de jeu supplémentaire en cas d'égalité."],
    ["TIRSAUBUT", "Séance de tirs pour départager deux équipes à égalité."],
    ["CHAMPIONNAT", "Compétition qui désigne le meilleur club sur une saison."],
    ["COUPE", "Compétition à élimination directe."],
    ["LIGUE", "Organisme qui organise les compétitions de football."],
    ["CLUB", "Association sportive regroupant une équipe de football."],
    ["SUPPORTER", "Personne qui encourage passionnément une équipe."],
    ["STADE", "Enceinte où se déroulent les matchs de football."],
    ["TRIBUNE", "Gradins où sont assis les spectateurs dans un stade."],
    ["ENTRAINEUR", "Personne qui dirige et prépare une équipe."],
    ["SELECTIONNEUR", "Entraîneur qui choisit les joueurs d'une équipe nationale."],
    ["TRANSFERT", "Changement de club d'un joueur."],
    ["CONTRAT", "Accord qui lie un joueur à son club."],
    ["REMPLACANT", "Joueur qui entre en jeu en cours de match."],
    ["BANC", "Endroit où sont assis les remplaçants et l'entraîneur."],
    ["BLESSURE", "Dommage physique qui empêche un joueur de jouer."],
    ["REPRISE", "Moment où le jeu recommence après une interruption."],
    ["MONDIAL", "Compétition qui réunit les meilleures équipes nationales du monde."],
    ["DERBY", "Match opposant deux équipes rivales de la même région."]
  ],
  "Histoire": [
    ["PREHISTOIRE", "Période avant l'apparition de l'écriture."],
    ["ANTIQUITE", "Période historique des grandes civilisations comme la Grèce et Rome."],
    ["MOYENAGE", "Période historique entre l'Antiquité et la Renaissance."],
    ["RENAISSANCE", "Période de renouveau artistique et intellectuel en Europe."],
    ["REVOLUTION", "Changement radical et souvent brutal d'un système politique."],
    ["EMPIRE", "Vaste territoire gouverné par un empereur."],
    ["ROYAUME", "Territoire gouverné par un roi ou une reine."],
    ["MONARCHIE", "Système politique dirigé par un souverain."],
    ["REPUBLIQUE", "Système politique où le pouvoir appartient au peuple par ses représentants."],
    ["DEMOCRATIE", "Système politique où le peuple exerce le pouvoir."],
    ["DICTATURE", "Régime où le pouvoir est exercé sans partage par une seule autorité."],
    ["GUERRE", "Conflit armé entre des groupes ou des nations."],
    ["PAIX", "Absence de conflit entre des groupes ou des nations."],
    ["TRAITE", "Accord officiel signé entre plusieurs parties."],
    ["ALLIANCE", "Union formée entre plusieurs parties pour un objectif commun."],
    ["CONQUETE", "Prise de possession d'un territoire par la force."],
    ["COLONISATION", "Installation d'un pouvoir sur un territoire étranger."],
    ["INDEPENDANCE", "Fait pour un territoire de ne plus dépendre d'un autre pouvoir."],
    ["ESCLAVAGE", "Système où des personnes sont privées de liberté et possédées."],
    ["REVOLTE", "Soulèvement contre une autorité."],
    ["INSURRECTION", "Soulèvement armé contre un pouvoir en place."],
    ["PHARAON", "Souverain de l'Égypte antique."],
    ["EMPEREUR", "Souverain qui dirige un empire."],
    ["ROI", "Souverain qui dirige un royaume."],
    ["REINE", "Souveraine qui dirige un royaume."],
    ["CHEVALIER", "Guerrier noble du Moyen Âge, souvent à cheval."],
    ["SEIGNEUR", "Noble qui possédait des terres au Moyen Âge."],
    ["NOBLESSE", "Classe sociale privilégiée héritant de titres."],
    ["PEUPLE", "Ensemble des habitants d'un pays ou d'une nation."],
    ["CIVILISATION", "Ensemble des caractéristiques culturelles d'une société."],
    ["PYRAMIDE", "Grand monument à base carrée construit par les pharaons."],
    ["CHATEAU", "Grande demeure fortifiée d'un seigneur ou d'un roi."],
    ["FORTERESSE", "Construction fortifiée destinée à la défense."],
    ["ARMEE", "Ensemble organisé de soldats."],
    ["SOLDAT", "Personne qui sert dans une armée."],
    ["BATAILLE", "Affrontement armé entre deux forces."],
    ["INVASION", "Entrée armée d'une force sur un territoire étranger."],
    ["EXPEDITION", "Voyage organisé, souvent d'exploration ou de conquête."],
    ["EXPLORATEUR", "Personne qui découvre des territoires inconnus."],
    ["DECOUVERTE", "Fait de trouver ou de comprendre quelque chose de nouveau."],
    ["ARCHEOLOGUE", "Scientifique qui étudie les vestiges du passé."],
    ["ARTEFACT", "Objet fabriqué par l'homme, étudié pour sa valeur historique."],
    ["VESTIGE", "Reste visible d'une civilisation disparue."],
    ["MONUMENT", "Construction commémorative ou historique."],
    ["DYNASTIE", "Succession de souverains issus de la même famille."],
    ["CONSTITUTION", "Texte fondamental qui organise les pouvoirs d'un État."],
    ["CITOYEN", "Membre d'un État ayant des droits et des devoirs."],
    ["ABOLITION", "Suppression officielle d'une loi ou d'un système."],
    ["ARMISTICE", "Accord qui suspend temporairement un conflit armé."],
    ["ARCHIVE", "Document conservé pour témoigner du passé."]
  ]
};

function difficultyOf(word) {
  if (word.length <= 6) return "facile";
  if (word.length <= 9) return "moyen";
  return "difficile";
}

// Liste plate : [{ mot, theme, difficulte, definition }]
const WORD_BANK = Object.entries(RAW_WORDS).flatMap(([theme, words]) =>
  words.map(([mot, definition]) => ({ mot, theme, difficulte: difficultyOf(mot), definition }))
);

const THEMES = Object.keys(RAW_WORDS);

function pickWord({ theme = null, difficulte = null } = {}) {
  let pool = WORD_BANK;
  if (theme && theme !== "Tous") pool = pool.filter(w => w.theme === theme);
  if (difficulte && difficulte !== "Tous") pool = pool.filter(w => w.difficulte === difficulte);
  if (pool.length === 0) pool = WORD_BANK;
  return pool[Math.floor(Math.random() * pool.length)];
}

function definitionOf(word) {
  const entry = WORD_BANK.find(w => w.mot === word);
  return entry ? entry.definition : null;
}

window.PenduWordBank = { WORD_BANK, THEMES, pickWord, difficultyOf, definitionOf };
